### ISSUE TITLE
constant(safe-area-inset-top), env(safe-area-inset-top) keeps viewport displaced in some edge cases

### ISSUE THREAD

**Issue by vinnichase** [AyogoHealth/cordova-plugin-wkkeyboardfix#2]
Hey Great Plugin!

Forgive me if I just throw the issue in this form but it might help the one or the other:

These CSS rules keep the viewport minimally displaced when an input field is slightly below the center (of the non-keyboard area). Haven't investigated further!

```CSS
body {
    padding-top: constant(safe-area-inset-top);
    padding-top: env(safe-area-inset-top);
}
```

I removed them from my app and everything works fine!
